apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "name" . }}
webhooks:
- name: shoots.mutation.alicloud.provider.extensions.gardener.cloud
  rules:
  - apiGroups:
    - core.gardener.cloud
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - UPDATE
    resources:
    - shoots
  admissionReviewVersions:
    - v1
    - v1beta1
  clientConfig:
    {{- if .Values.global.virtualGarden.enabled }}
    url: {{ printf "https://%s.%s/webhooks/mutate/shoots" (include "name" .) (.Release.Namespace) }}
    {{- else }}
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "name" . }}
      path: /webhooks/mutate/shoots
    {{- end }}
    caBundle: {{ required ".Values.webhookConfig.caBundle is required" (b64enc .Values.global.webhookConfig.caBundle) }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  namespaceSelector: {}
  objectSelector: {}
  sideEffects: None
  timeoutSeconds: 10
